default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: insta_clone_development

test:
  <<: *default
  database: insta_clone_test

production:
  <<: *default
  database: insta_clone_production
  username: insta_clone
  password: <%= ENV['INSTA_CLONE_DATABASE_PASSWORD'] %>